# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: gjIT
email: yougra79@yahoo.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Welcome to gjIT.co.uk. Please take a look at our portfolio of work which includes web design, data visualisation, 
  aspects of data science and UX/UI design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: gjIT


# Build settings
markdown: kramdown

theme: jekyll-theme-slate
